language: java
jdk:
  - openjdk8

script: "mvn cobertura:cobertura deploy -Dregistry=https://maven.pkg.github.com/phanatic -Dtoken=$GH_TOKEN"

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

