language: java
jdk:
  - openjdk8
#  - openjdk11

#install:
#  - npm install -g snyk
#  - snyk test

env:
  - CODECOV_TOKEN="08d55f18-b52c-4663-b1ad-f45412981bc3"

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - snyk monitor

